apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yacreader-server.fullname" . }}
  labels:
    {{- include "yacreader-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "yacreader-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "yacreader-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PUID
              value: {{ .Values.env.PUID | quote }}
            - name: PGID
              value: {{ .Values.env.PGID | quote }}
            - name: TZ
              value: {{ .Values.env.TZ | quote }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
            - name: comics
              mountPath: {{ .Values.persistence.comics.mountPath }}
      volumes:
        - name: config
          {{- if .Values.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "yacreader-server.fullname" . }}-config
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: comics
          {{- if .Values.persistence.comics.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "yacreader-server.fullname" . }}-comics
          {{- else }}
          emptyDir: {}
          {{- end }}
