{{- if .Values.persistence.config.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "yacreader-server.fullname" . }}-config
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
{{- end }}
---
{{- if .Values.persistence.comics.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "yacreader-server.fullname" . }}-comics
spec:
  accessModes:
    - {{ .Values.persistence.comics.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.comics.size | quote }}
{{- end }}
