apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freedns-updater.fullname" . }}-tokens
  labels:
    {{- include "freedns-updater.labels" . | nindent 4 }}
type: Opaque
data:
  tokens: {{ .Values.tokens | join "," | b64enc | quote }}
